server:
  port: 5001

spring:
  application:
    name: USER-SERVICE

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true # Show SQL statements
  datasource:
    url: jdbc:mysql://localhost:3306/Task
    username: root
    password: Anjanawwe123#
    driver-class-name: com.mysql.cj.jdbc.Driver
