server:
  port: 5002

spring:
  application:
    name: TASK-SERVICE

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true # Show SQL statements
  datasource:
    url: jdbc:mysql://localhost:3306/task_service
    username: root
    password: Anjanawwe123#
    driver-class-name: com.mysql.cj.jdbc.Driver
